export enum JaPosTags {
    English_word = "E",
    Adjective_Common = "A-c",
    Adjective_Dependent = "A-dp",
    Adjectival_Noun_Common = "J-c",
    Adjectival_Noun_Tari = "J-tari",
    Adjectival_Noun_AuxVerb_stem = "J-xs",
    Pronoun = "D",
    Interjection_Common = "I-c",
    Adverb = "F",
    //Auxiliary_sign_AA = "M-aa",
    //Auxiliary_sign_Common = "M-c",
    //Auxiliary_sign_Open_Parenthesis = "M-cp",
    //Auxiliary_sign_Close_Parenthesis = "M-op",
    //Auxiliary_sign_Period = "M-p",
    Noun_Noun = "N-n",
    Noun_Common_Noun = "N-nc",
    Noun_Proper_Noun = "N-pn",
    Noun_AuxVerb_stem = "N-xs",
    Others = "O",
    Prefix = "P",
    Particle_Adverbial = "P-fj",
    Particle_Phrasal = "P-jj",
    Particle_Case_Marking = "P-k",
    Particle_Binding = "P-rj",
    Particle_Conjunctive = "P-sj",
    Suffix_Adjective = "Q-a",
    Suffix_Adjectival_Noun = "Q-j",
    Suffix_Noun = "Q-n",
    Suffix_Verb = "Q-v",
    Adnominal_adjective = "R",
    Sign_Common = "S-c",
    Sign_Letter = "S-l",
    //URL = "U",
    Verb_Common = "V-c",
    Verb_Dependent = "V-dp",
    Whitespace = "W",
    AuxVerb = "X",
  }


  