/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type TokenizedSubtitleResponseDto = {
  tokens: {
    reading: string;
    text: string;
    kana: string;
    score: number;
    seq: number;
    compound: string[];
    components: {
      reading: string;
      text: string;
      kana: string;
      score: number;
      seq: number;
      conj: {
        prop: {
          pos: string;
          type: string;
        }[];
        reading: string;
        gloss: {
          pos: string;
          gloss: string;
          info: string;
        };
      };
    }[];
    gloss: {
      pos: string;
      gloss: string;
      info: string;
    }[];
    conj: {
      prop: {
        pos: string;
        type: string;
      }[];
      reading: string;
      gloss: {
        pos: string;
        gloss: string;
        info: string;
      };
    }[];
  }[];
  start: number;
  end: number;
};

export type SubtitleResponseDto = {
  text: string;
  start: number;
  end: number;
};
