// This file is auto-generated by @hey-api/openapi-ts

export const TokenizedSubtitleResponseDtoSchema = {
    type: 'object',
    properties: {
        tokens: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    reading: {
                        type: 'string'
                    },
                    text: {
                        type: 'string'
                    },
                    kana: {
                        type: 'string'
                    },
                    score: {
                        type: 'number'
                    },
                    seq: {
                        type: 'number'
                    },
                    compound: {
                        type: 'array',
                        items: {
                            type: 'string'
                        }
                    },
                    components: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                reading: {
                                    type: 'string'
                                },
                                text: {
                                    type: 'string'
                                },
                                kana: {
                                    type: 'string'
                                },
                                score: {
                                    type: 'number'
                                },
                                seq: {
                                    type: 'number'
                                },
                                conj: {
                                    type: 'object',
                                    properties: {
                                        prop: {
                                            type: 'array',
                                            items: {
                                                type: 'object',
                                                properties: {
                                                    pos: {
                                                        type: 'string'
                                                    },
                                                    type: {
                                                        type: 'string'
                                                    }
                                                },
                                                required: ['pos', 'type']
                                            }
                                        },
                                        reading: {
                                            type: 'string'
                                        },
                                        gloss: {
                                            type: 'object',
                                            properties: {
                                                pos: {
                                                    type: 'string'
                                                },
                                                gloss: {
                                                    type: 'string'
                                                },
                                                info: {
                                                    type: 'string'
                                                }
                                            },
                                            required: ['pos', 'gloss', 'info']
                                        }
                                    },
                                    required: ['prop', 'reading', 'gloss']
                                }
                            },
                            required: ['reading', 'text', 'kana', 'score', 'seq', 'conj']
                        }
                    },
                    gloss: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                pos: {
                                    type: 'string'
                                },
                                gloss: {
                                    type: 'string'
                                },
                                info: {
                                    type: 'string'
                                }
                            },
                            required: ['pos', 'gloss', 'info']
                        }
                    },
                    conj: {
                        type: 'array',
                        items: {
                            type: 'object',
                            properties: {
                                prop: {
                                    type: 'array',
                                    items: {
                                        type: 'object',
                                        properties: {
                                            pos: {
                                                type: 'string'
                                            },
                                            type: {
                                                type: 'string'
                                            }
                                        },
                                        required: ['pos', 'type']
                                    }
                                },
                                reading: {
                                    type: 'string'
                                },
                                gloss: {
                                    type: 'object',
                                    properties: {
                                        pos: {
                                            type: 'string'
                                        },
                                        gloss: {
                                            type: 'string'
                                        },
                                        info: {
                                            type: 'string'
                                        }
                                    },
                                    required: ['pos', 'gloss', 'info']
                                }
                            },
                            required: ['prop', 'reading', 'gloss']
                        }
                    }
                },
                required: ['reading', 'text', 'kana', 'score', 'seq', 'compound', 'components', 'gloss', 'conj']
            }
        },
        start: {
            type: 'number'
        },
        end: {
            type: 'number'
        }
    },
    required: ['tokens', 'start', 'end']
} as const;