// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { AppControllerGetTokenizedSubtitlesData, AppControllerGetTokenizedSubtitlesError, AppControllerGetTokenizedSubtitlesResponse, AppControllerGetTokenizedSubtitleData, AppControllerGetTokenizedSubtitleError, AppControllerGetTokenizedSubtitleResponse, AppControllerGetSubtitlesData, AppControllerGetSubtitlesError, AppControllerGetSubtitlesResponse } from './types.gen';

export const client = createClient(createConfig());

export const appControllerGetTokenizedSubtitles = <ThrowOnError extends boolean = false>(options: Options<AppControllerGetTokenizedSubtitlesData, ThrowOnError>) => { return (options?.client ?? client).get<AppControllerGetTokenizedSubtitlesResponse, AppControllerGetTokenizedSubtitlesError, ThrowOnError>({
    ...options,
    url: '/subtitleToken/{id}'
}); };

export const appControllerGetTokenizedSubtitle = <ThrowOnError extends boolean = false>(options: Options<AppControllerGetTokenizedSubtitleData, ThrowOnError>) => { return (options?.client ?? client).post<AppControllerGetTokenizedSubtitleResponse, AppControllerGetTokenizedSubtitleError, ThrowOnError>({
    ...options,
    url: '/subtitleToken'
}); };

export const appControllerGetSubtitles = <ThrowOnError extends boolean = false>(options: Options<AppControllerGetSubtitlesData, ThrowOnError>) => { return (options?.client ?? client).get<AppControllerGetSubtitlesResponse, AppControllerGetSubtitlesError, ThrowOnError>({
    ...options,
    url: '/subtitles/{id}'
}); };