// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { AppControllerGetTokenizedSubtitlesData, AppControllerGetTokenizedSubtitlesError, AppControllerGetTokenizedSubtitlesResponse } from './types.gen';

export const client = createClient(createConfig());

export const appControllerGetTokenizedSubtitles = <ThrowOnError extends boolean = false>(options: Options<AppControllerGetTokenizedSubtitlesData, ThrowOnError>) => { return (options?.client ?? client).get<AppControllerGetTokenizedSubtitlesResponse, AppControllerGetTokenizedSubtitlesError, ThrowOnError>({
    ...options,
    url: '/subtitles/{id}'
}); };