// This file is auto-generated by @hey-api/openapi-ts

export type TokenizedSubtitleResponseDto = {
    tokens: Array<{
        reading: string;
        text: string;
        kana: string;
        score: number;
        seq: number;
        compound: Array<(string)>;
        components: Array<{
            reading: string;
            text: string;
            kana: string;
            score: number;
            seq: number;
            conj: {
                prop: Array<{
                    pos: string;
                    type: string;
                }>;
                reading: string;
                gloss: {
                    pos: string;
                    gloss: string;
                    info: string;
                };
            };
        }>;
        gloss: Array<{
            pos: string;
            gloss: string;
            info: string;
        }>;
        conj: Array<{
            prop: Array<{
                pos: string;
                type: string;
            }>;
            reading: string;
            gloss: {
                pos: string;
                gloss: string;
                info: string;
            };
        }>;
    }>;
    start: number;
    end: number;
};

export type AppControllerGetTokenizedSubtitlesData = {
    path: {
        id: string;
    };
};

export type AppControllerGetTokenizedSubtitlesResponse = (Array<TokenizedSubtitleResponseDto>);

export type AppControllerGetTokenizedSubtitlesError = unknown;